### ISSUE TITLE
Maintainers wanted

### ISSUE THREAD

**Issue by errordeveloper** [errordeveloper/oe-meta-go#8]
Hey folks, I've been far too busy working on many different things at my day job, so I completely missed all the pull requests here. To be honest I was very pleased this repo got so popular!

I have just merged a few changes that I could, and will attempt cherry picking the remaining ones.

I can see that quite a few of you have active forks, so I am happy to discuss the future of this layer.
## 

_cc @mem @rstrand @pasinskim @dllarson @lukaszgemborowski @agherzan @telphan @masselstine_

**Comment by errordeveloper** [comment]
_cc @lifupan @paw3142 @avalluri_

**Comment by lukaszgemborowski** [comment]
At least now I do not have a time to continue my project and for maintaining any yocto layer. I don't think that you need any of my commit(s). This was just a temporary fix for some build problem that I faced, so my commit(s) are more like workarounds for my lack of knowledge. :)

Anyway if I find some spare time to get back to my project I can of course support this layer.

**Comment by mem** [comment]
Nice!

I've been cleaning up my fork to upgrade to krogoth.

The thing I don't have a good answer for just yet is how to provide Go packages for Yocto, and in particular libraries.

For example, in my fork I provide Caddy as an example of how to do this. I took the approach of having every single Go package that Caddy depends on provided a Bitbake recipe of its own. The problem with that approach is that it's very cumbersome, but that's something that you can live with. The other problem with the approach is that Go doesn't really have versions (see here: http://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases) and therefore it's hard to know what can be packaged. Furthermore, you need to figure out a whole bunch of SRCREVs that the upstream author probably hasn't figured out himself.

And I ran into an interesting issue: we speak of golang.org/x/net/context, but in reality that's a package, but not a repository. The repository is actually github.com/golang/net, and it contains a directory called context. So having a recipe for golang.org/x/net means that it provides many packages. The many packages do not gain you anything as Go will do a good job of figuring out what needs to be built. But, this is the interesting bit, buried in golang.org/x/net there's a package that depends on something buried in golang.org/x/crypto. And there's a different something in golang.org/x/crypto that depends on a different bit of golang.org/x/net. So a recipe for golang.org/x/net cannot have the equivalent DEPENDS += "golang.org/x/crypto" because the later has a DEPENDS += "golang.org/x/net".

How are you dealing with something like that?

**Comment by mem** [comment]
I just pushed all the changes I have to mem/oe-meta-go

**Comment by errordeveloper** [comment]
Hey @mem, I'm happy for you to take over, and sorry for the delay (I've been quite busy with my day job at @Weaveworks). I've updated the description of this repo.
